# Generated by Django 4.2.1 on 2023-05-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user/avatars/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
