# Generated by Django 4.2.1 on 2023-05-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='media/user/avatars/23/05/17/default.jpg', upload_to='user/avatars/%y/%m/%d'),
        ),
    ]
